[versions]
androidxPaging3Extensions = "2.0.1"
jtokkit = "0.6.1"
pagingVersion = "3.3.0"
precompose = "1.6.0"
project-versionCode = "64"
project-versionName = "2.8.1"
agp = "8.1.4"
android-compileSdk = "34"
android-minSdk = "24"
android-targetSdk = "33"
android-tools = "34.0.0"
androidx-activityCompose = "1.7.1"
androidx-appcompat = "1.6.1"
androidx-constraintlayout = "2.1.4"
androidx-core-ktx = "1.12.0"
androidx-espresso-core = "3.6.1"
androidx-material = "1.11.0"
androidx-test-junit = "1.2.1"
compose = "1.7.0-alpha01"
compose-bom = "2024.06.00"
compose-compiler = "1.5.6"
junit = "4.13.2"
kotlin = "1.9.23"
kotlinxSerialization = "1.5.1"
kotlinCoroutines = "1.8.0"
sqlDelight = "2.0.2"
sqliteJdbcDriver = "3.36.0"
androidxLifecycle = "2.8.3"
libres = "1.2.2"
buildKonfig = "0.15.1"

[libraries]
# Kotlin
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "pagingVersion" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "pagingVersion" }
jtokkit = { module = "com.knuddels:jtokkit", version.ref = "jtokkit" }
kotlin-compose-gradle = { group = "org.jetbrains.compose", name = "compose-gradle-plugin", version.ref = "compose" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlin-kotlinTestCommon = { group = "org.jetbrains.kotlin", name = "kotlin-test-common", version.ref = "kotlin" }
kotlin-kotlinTestJs = { group = "org.jetbrains.kotlin", name = "kotlin-test-js", version.ref = "kotlin" }
kotlin-kotlinTestAnnotationsCommon = { group = "org.jetbrains.kotlin", name = "kotlin-test-annotations-common", version.ref = "kotlin" }

kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
# immutable list
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version = "0.3.7" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# Android X
androidx-r8 = { group = "com.android.tools", name = "r8", version = "8.2.33" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-lifecycle-common = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version = "1.7.1" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.3.2" }

# Compose
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material = { module = "androidx.compose.material:material3" }
compose-ui-android = { module = "androidx.compose.ui:ui-android" }

# SQLDelight
sqldelight-primitive-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqlDelight" }
sqldelight-runtime = { group = "app.cash.sqldelight", name = "runtime", version.ref = "sqlDelight" }
sqldelight-driver = { group = "app.cash.sqldelight", name = "sqlite-driver", version.ref = "sqlDelight" }
sqldelight-android-driver = { group = "app.cash.sqldelight", name = "android-driver", version.ref = "sqlDelight" }
sqldelight-native-driver = { group = "app.cash.sqldelight", name = "native-driver", version.ref = "sqlDelight" }
sqldelight-coroutines-extensions = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqldelight-androidx-paging3-extensions = { module = "app.cash.sqldelight:androidx-paging3-extensions", version.ref = "androidxPaging3Extensions" }

# Thirld-party
rhino = { group = "org.mozilla", name = "rhino", version = "1.7.13" } # 1.7.14 is not compatible with Android, see https://github.com/mozilla/rhino/issues/1149
# com.github.gedoor:rhino-android:1.8
rhino-android = { group = "com.github.gedoor", name = "rhino-android", version = "1.8" }
libres-compose = { module = "io.github.skeptick.libres:libres-compose", version.ref = "libres" }
mmkv = { group = "com.tencent", name = "mmkv", version = "1.3.2" }
precompose = { module = "moe.tlaster:precompose", version.ref = "precompose" }
precompose-viewmodel = { module = "moe.tlaster:precompose-viewmodel", version.ref = "precompose" }

# Dependencies of the included build-logic
gradle-plugin-android-tools = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
gradle-plugin-android-common = { group = "com.android.tools", name = "common", version.ref = "android-tools" }
gradle-plugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
#ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
#work-testing = { group = "androidx.work", name = "work-testing", version = "2.9.0" }
gradle-plugin-sqldelight = { group = "app.cash.sqldelight", name = "gradle-plugin", version.ref = "sqlDelight" }
gradle-plugin-libres = { group = "io.github.skeptick.libres", name = "gradle-plugin", version.ref = "libres" }
gradle-plugin-buildKonfig = { group = "com.codingfeline.buildkonfig", name = "buildkonfig-gradle-plugin", version.ref = "buildKonfig" }
gradle-plugin-buildKonfig-compiler = { group = "com.codingfeline.buildkonfig", name = "buildkonfig-compiler", version.ref = "buildKonfig" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mokoResourcesGenerator = { id = "dev.icerock.mobile.multiplatform-resources", version = "0.23.0" }
# io.github.skeptick.libres:gradle-plugin:1.2.2
libres = { id = "io.github.skeptick.libres", version.ref = "libres" }
# 'com.codingfeline.buildkonfig:buildkonfig-gradle-plugin:latest_version'
buildKonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }
sqlDelight = { id = "app.cash.sqldelight", version.ref = "sqlDelight" }
# org.jetbrains.kotlin.plugin.compose
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


# Plugins defined by this project
transtation-kmp-thirdpartyplugins = { id = "transtation.kmp.thirdpartyplugins", version = "unspecified" }
transtation-kmp-library = { id = "transtation.kmp.library", version = "unspecified" }
transtation-kmp-application = { id = "transtation.kmp.application", version = "unspecified" }

[bundles]
#stately = ["stately-common","stately-concurrency","stately-isolate","stately-iso-collections"]
androidx-lifecycle = ["androidx-lifecycle-common","androidx-lifecycle-runtime"]
androidx-common = ["androidx-activity-compose","androidx-core-ktx"]
kotlin-test = ["kotlin-kotlinTestCommon","kotlin-kotlinTestAnnotationsCommon"]
sqldelight = ["sqldelight-runtime","sqldelight-coroutines-extensions","sqldelight-driver"]
#mviKotlin = ["mviKotlin-dep","mviKotlin-main","mviKotlin-coroutines","mviKotlin-logging","mviKotlin-timetravel"]
kotlinCommon = ["kotlin-coroutines", "kotlinx-serialization-json"]
kotlinCoroutines = ["kotlin-coroutines"]